### PR TITLE
Key-homomorphic PRF merge

### PR DESCRIPTION
**Pull request by nskins**
The key-homomorphic PRF implementation is ready to be merged into cpeikert/Lol.

~~This merge also fixes an ambiguity issue by hiding the numeric-prelude Matrix from some Tensor files.~~

### CODE REVIEW

**Comment by crockeea** [comment]
We're working on some simple interfaces to major portions of the library. The hope is that all applications can import `Crypto.Lol` and be done with it. It looks like this should work for your application, can you give it a try?

**Comment by nskins** [comment]
Yes, I changed it as you suggested and it's working.

**Comment by crockeea** [comment]
It would also be great to have a simple example of how to use the PRF with concrete types and values. Examples should go in apps/examples/.

**Comment by nskins** [comment]
I developed the PRF example in a similar manner to the SHE example, which acts as both a guide for the user and as test cases. I've provided examples on how to use all of the exported types/functions and comments for a simple use case.

**Comment by cpeikert** [comment]
Closing this to get a new target branch; github can't edit the target??: https://github.com/isaacs/github/issues/18

**Pull request closed without merging**
